#!/bin/sh
# MySQL daemon start/stop script.

# Usually this is put in /etc/init.d (at least on machines SYSV R4 based
# systems) and linked to /etc/rc3.d/S99mysql and /etc/rc0.d/K01mysql.
# When this is done the mysql server will be started when the machine is
# started and shut down when the systems goes down.

# Comments to support chkconfig on RedHat Linux
# chkconfig: 2345 64 36
# description: A very fast and reliable SQL database engine.

## BEGIN INIT INFO
# Provides: mysql
# Required-Start: $local_fs $network $remote_fs
# Should-Start: ypbind nscd ldap ntpd xntpd
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop MySQL
# Description: MySQL is a very fast and reliable SQL database engine.
## END INIT INFO


port="3306"
my_user="root"
my_pwd="mysql123"
my_cmd="/applications/mysql/bin/mysqld_safe"
my_admin="/applications/mysql/bin/mysqladmin"
my_sock=/data/${port}/mysql.sock
my_cnf=/data/${port}/my.cnf
my_log=/data/${port}/log/mysql_install.err
my_status=`netstat -lntup|grep ${port}|wc -l`


function rmsg() { echo -e "\033[31;49m$*\033[0m"; }
function gmsg() { echo -e "\033[32;49m$*\033[0m"; }
function bmsg() { echo -e "\033[34;49m$*\033[0m"; }


function start() {
    # start mysql service
    echo -n "Starting MySQL... "
    if [ ! -e $my_sock -a $my_status -ne "1" ]; then
        ${my_cmd} --defaults-file=${my_cnf} >${my_log} 2>&1 &
        sleep 3
        my_status=`netstat -lntup|grep ${port}|wc -l`
        if [ -e $my_sock -a $my_status -eq "1" ]; then
            gmsg "SUCCESS!"
            echo ""
        else
            rmsg "Failed"
            exit 1
        fi
    else
        rmsg "Failed"
        bmsg "MySQL is running..."
        echo ""
    fi
}


function stop() {
    # stop mysql service
    if [ ! -e $my_sock -a $my_status -ne "1" ]; then
        echo "MySQL is stopped..."
        echo ""
    else
        echo -n "Stoping MySQL... "
        ${my_admin} -u${my_user} -p${my_pwd} -S ${my_sock} shutdown >$my_log 2>&1
        my_status=`netstat -lntup|grep ${port}|wc -l`
        if [ ! -e $my_sock -a $my_status -ne "1" ]; then
            gmsg "SUCCESS"
            echo ""
        else
            rmsg "Failed"
            exit 1
        fi
    fi
}


function restart() {
    # restart mysql service
    echo -e "Restarting MySQL... \n"
    stop
    sleep 3
    start
}


function status() {
    my_pid=`ps -ef|grep "^mysql"|grep ${port}|awk -F " " '{print $2}'`
    if [ -e $my_sock -a $my_status -eq "1" ]; then
        gmsg "MySQL service is running..."
        gmsg "PID: $my_pid"
        echo ""
    else
        rmsg "MySQL service no run."
        echo ""
    fi
}


case $1 in
    start )
        start
        ;;
    stop )
        stop
        ;;
    restart )
        restart
        ;;
    status )
        status
        ;;
    help|* )
        echo "USAGE: $0 /data/${port}/mysqld {start|stop|restart|status}"
        cat <<EOF

        start     - start mysql service
        stop      - stop mysql service
        status    - show current status of mysql service
        restart   - restart mysql service if running by sending a SIGHUP or start if not running
        help      - this screen

EOF
        exit 1
        ;;
esac
